name: career_coach
description: "CareerCoach - Career Roadmap & Guidance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  lucide_icons: ^0.257.0
  shared_preferences: ^2.5.4
  animations: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

